%% Full One-Stage Utility Function

%% Function
function one_stage_utility = u_xa(t, l, p, tau, m, h, d_tilde, m_tilde, p_tilde, ...
                                   theta_t_shop, theta_home_t, delta_t, ...
                                   x_pls, theta_shop_s, theta_C_shop, theta_size_shop, ...
                                   theta_work_t, t_work_start_after, t_work_start_before, ...
                                   theta_mode_constant, theta_TT_mode, theta_cost, theta_sz_walk, ...
                                   time_cost_data)
    % u_xa: Computes utility for one stage of decision/action
    
    if m_tilde == "stay" && tau == 0
        % Staying and starting an activity
        one_stage_utility = ...
            u_act(t, p_tilde, tau, theta_t_shop, theta_home_t, delta_t) + ...
            u_start(l, t, h, p_tilde, ...
                    x_pls, theta_shop_s, theta_C_shop, theta_size_shop, ...
                    theta_work_t, t_work_start_after, t_work_start_before);
    else
        % Traveling
        one_stage_utility = ...
            u_travel(t, l, m, m_tilde, d_tilde, ...
                     theta_mode_constant, theta_TT_mode, ...
                     theta_cost, theta_sz_walk, time_cost_data);
    end
end
